config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :user
  resources :users
  resources :people
  resources :events
  resources :teams


  resources :locations
  resources :regions

  resources :event_role_types
  resources :event_types

  resources :team_role_types
  resources :team_types

  resources :person_event_assignments
  resources :person_team_assignments

  resources :calls

  resources :import_jobs,         only: [:index, :show, :destroy]

  resource :import_teilnehmer,   only: [:new, :create]
  resource :import_absolventen,  only: [:new, :create]

  resource :export_absolventen,  only: [:new, :create]

  resources :report, only: [:index, :show] do
    get :export
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id             :integer          not null, primary key
#  region_id      :integer
#  firstname      :string(255)
#  lastname       :string(255)
#  callby         :string(255)
#  sex            :string(255)
#  title          :string(255)
#  country        :string(255)
#  region         :string(255)
#  zip            :string(255)
#  city           :string(255)
#  street         :string(255)
#  housenumber    :string(255)
#  birthday       :date
#  email          :string(255)
#  state          :string(255)
#  date           :string(255)
#  phone_private  :string(255)
#  phone_work     :string(255)
#  phone_mobile   :string(255)
#  notes          :text(65535)
#  do_not_contact :boolean
#


class Person < ActiveRecord::Base

  nilify_blanks

  # track changes to model data
  has_paper_trail

  extend Enumerize

  enumerize :sex, in: [:other, :female, :male]

  after_initialize :set_default_values, :if => :new_record?

  before_validation {if self.id.blank? then self.id = Person.new_pid end} # in theory this could give the same pid for two concurrent actions

  has_many :calls
  has_many :person_team_assignments
  has_many :person_event_assignments

  belongs_to :region

  # validates :sex,      presence: true
  validates :id,        presence: true
  validates :lastname,  presence: true
  validates :country,   presence: true

  def self.search(search)
    if search
      people = where("id > 1")
      people = people.where("id = ?",           "#{search[:pid]}" )       if search[:pid].present?
      people = people.where("lastname like ?",  "#{search[:lastname]}%" ) if search[:lastname].present?
      people = people.where("country = ?",      "#{search[:country]}" )   if search[:country].present?
      people = people.where("zip like ?",       "#{search[:zip]}%" )      if search[:zip].present?
      people = people.where("city like ?",      "#{search[:city]}%" )     if search[:city].present?
      people
    else
      where(nil)
    end

  end

  def self.new_pid
    1 + Person.maximum(:id).to_i
  end


  def fullname
    "#{lastname}, #{firstname}"
  end
  def to_s
    "#{lastname}, #{firstname} #{country}-#{zip} #{city}"
  end

  def assign_to_event(event, role)
    unless person_event_assignments.exists?(event: event)
      person_event_assignments.create!(event: event, event_role_type: role)
    end
  end

  def event_assignments
    person_event_assignments.joins(:event).order("events.startdate DESC")
  end

  def team_assignments
    person_team_assignments # .joins(group: :group_type).merge(GroupType.team)
  end

  def salutation
    I18n.translate self.sex
  end

  def salutation=(value)
    case value
      when "Herr"
        self.sex = :male
      when "Frau"
        self.sex = :female
      else
        self.sex = :other
    end
  end

  def callby=(name)
    super unless name==self.firstname
  end

  def country=(value="DE")
    if value == "D"
      self.country="DE"
    elsif value.nil?
      # do nothing
    else
      super
    end
  end

  def region=(region)
    return if region.blank?

    r = Region.where(code: region).first
    if r
      super r
    else
      super Region.create!(code: region)
    end
  end


  def status=(value)
    if value == "DNC"
      self.do_not_contact = true
    end
  end

  def ooa_es=(value)
    if value == "Y" || value == "y" || value == "J" || value == "j"
      super true
    else
      super value # don't overwrite a nil value with false
    end
  end

  def ooa_sem=(value)
    if value == "Y" || value == "y" || value == "J" || value == "j"
      super true
    else
      super value # don't overwrite a nil value with false
    end
  end

  private
  def set_default_values
    self.country ||= "DE"
  end

end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_filter :authenticate_user!

  before_action :find_person, only: [:show, :edit, :update, :destroy]
  after_action  :verify_authorized

  respond_to :html

  VISIBLE_ATTRIBUTES =
    %w(id title sex firstname callby lastname birthday email country zip city street housenumber
                    state date
                    phone_private phone_work phone_mobile region ooa_es ooa_sem)

  def index
    @persons = Person.search(filter_params).take(15)
    authorize Person
  end

  def show
    authorize @person
    case params[:person_tabs_selected_tab]
    when 'person', nil then
      @data = @person
      per_page = 1
    when 'events' then
      @data = @person.event_assignments
      per_page = 8
    when 'teams'
      @data = @person.team_assignments
      per_page = 8
    when 'calls'
      @data = @person.calls
      per_page = 10
    when 'history'
      @data = @person.versions
      per_page = 1
    else
      @data = nil
    end

    if @data.respond_to? :page
      @data = @data.page(params[:page]).per(per_page)
    end

  end

  def new
    @person = Person.new
    authorize @person
    # respond_with @person
  end

  def create
    @person = Person.new(secure_create_params)
    authorize @person

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @person = Person.find(params[:id])
    authorize @person
    respond_with @person
  end

  def update

    authorize @person
    if @person.update(secure_update_params)
      # respond_with(@person, :notice => "Person updated.")
      redirect_to person_path(person_tabs_selected_tab: 'history'), :notice => "Person updated."
    else
      render :edit
    end

    #if @person.update_attributes(secure_params)
    #  redirect_to person_path, :notice => "Person updated."
    #else
    #  #format.html { render :edit, @person}
    #  redirect_to edit_person_path(@person), :alert => "Unable to update person. #{@person.errors.messages}"
    #end
  end

  def destroy
    authorize @person
    @person.destroy
    redirect_to person_path, :notice => "Person deleted."
  end

  private
  def find_person
    @person = Person.find(params[:id])
  end

  def secure_update_params
    params
      .require(:person)
      .permit(:title, :firstname, :lastname, :callby,
              :birthday, :sex, :country,
              :zip, :city, :street, :housenumber, :email,
              :state, :date,
              :phone_private, :phone_work, :phone_mobile,
              :do_not_contact, :ooa_es, :ooa_sem,
              :region)
  end
  def secure_create_params
    secure_update_params.permit(:id)
  end

  def filter_params
    if params[:person]
      @filter = params.require(:person)
    else
      @filter = params
    end
    @filter.permit(:id, :lastname, :country, :zip, :city)
  end

end

app/views/people/_calls.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Datum</th>
      <th>Von</th>
      <th>Info</th>
    </tr>
  </thead>
  <% @data.each do |call| %>
    <tr>
      <td><%= localize call.date, :format => :short %></td>
      <td><%= call.caller %></td>
      <td><%= call.info %></td>
      <td><%# link_to 'Show', call %></td>
      <td><%# link_to 'Edit', edit_call_path(call) %></td>
      <td><%= link_to 'Remove', call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

  <% end %>
</table>

<div>
  <%= paginate @data %>
</div>

<div>
  <%= link_to 'Add new call', new_call_path(person: person), {class: "btn btn-default"} %>
</div>

app/views/people/_events.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>Datum</th>
        <th>Event</th>
        <th>Rolle</th>
      </tr>
    </thead>
    <% @data.each do |assignment| %>
      <tr>
        <td><%= assignment.event.startdate %></td>
        <td>
            <%= link_to assignment.event do %>
              <%= "#{assignment.event.event_type.description}" %>
              </br>
              <%= "#{assignment.event.title}" %>
            <% end %>
        </td>
        <td><%= assignment.event_role_type %></td>
        <td><%# link_to 'Show', assignment %></td>
        <td><%# link_to 'Edit', edit_person_event_assignment_path(assignment) %></td>
        <td><%= link_to 'Remove', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

    <% end %>
  </table>

  <div>
    <%= paginate @data %>
  </div>

  <div>
  <%= link_to 'Assign to new event', new_person_event_assignment_path(person: person), {class: "btn btn-default"} %>
  </div>

app/views/people/_history.html.erb
  <table class="table">
    <% @data.each do |version| %>
      <tr>
        <td><%= t version.event %></td>
        <td colspan="4">am: <%= l version.created_at, format: :short %>
                     von: <%= find_version_author_name(version) %></td>
      </tr>
      <% version.changeset.each do |change| %>
        <tr>
          <td></td>
          <td><%= t change[0], scope: 'simple_form.Person' %></td>
          <td><%= change[1][0] %></td>
          <td> => </td>
          <td><%= change[1][1] %></td>
        </tr>
      <% end %>
    <% end %>
  </table>

<div>
  <%= paginate @data %>
</div>

app/views/people/_person.html.erb
<div class="row">
<% show_object @person, only: controller.class::VISIBLE_ATTRIBUTES %>
<%= horizontal_form @person, readonly: true do |f| %>
  <div class="col-md-6">

  <%= f.input :id %>
  <%= f.input :title %>
  <%= f.input :sex, collection: Person.sex.options %>
  <%= f.input :firstname %>
  <%= f.input :callby %>
  <%= f.input :lastname  %>
  <%= f.input :birthday, as: :string %>
  <%= f.input :country, priority_countries: ["GB", "FR", "DE"] %>
  <%= f.input :zip %>
  <%= f.input :city %>
  <%= f.input :street %>
  <%= f.input :housenumber %>
  </div>

  <div class="col-md-6">
  <%= f.input :phone_private %>
  <%= f.input :phone_work %>
  <%= f.input :phone_mobile %>

  <%= f.input :state %>
  <%= f.input :date %>

  <%= f.input :do_not_contact, as: :boolean %>

  <%= f.input :ooa_es,  as: :boolean %>
  <%= f.input :ooa_sem, as: :boolean %>
  <%= f.input :region, collection: Region.all %>
  </div>

<% end %>

</div>

<div>
  <%= link_to I18n.t(:edit), edit_person_path(@person), {class: "btn btn-default"} %>
</div>

app/views/people/_person_edit.html.erb
<%= horizontal_form @person do |f| %>

  <div class="row">
  <%= f.error_notification %>
  </div>

  <div class="row">
  <div class="col-md-6">

  <%= f.input :id, readonly: true %>
  <%= f.input :title %>
  <%= f.input :sex, collection: Person.sex.options %>
  <%= f.input :firstname %>
  <%= f.input :callby %>
  <%= f.input :lastname  %>
  <%= f.input :birthday, include_blank: true, start_year: 1900, end_year: Date.today.year %>
  <%= f.input :country, priority_countries: ["GB", "FR", "DE"] %>
  <%= f.input :zip %>
  <%= f.input :city %>
  <%= f.input :street %>
  <%= f.input :housenumber %>
  </div>

  <div class="col-md-6">
  <%= f.input :phone_private %>
  <%= f.input :phone_work %>
  <%= f.input :phone_mobile %>

  <%= f.input :state %>
  <%= f.input :date %>

  <%= f.input :do_not_contact, as: :boolean %>

  <%= f.input :ooa_es,  as: :boolean %>
  <%= f.input :ooa_sem, as: :boolean %>
  <%= f.input :region, collection: Region.all %>
  </div>
  </div>

  <div class="row">
  <%= f.button :submit %>
  <%= link_to "Abbruch", :back, {:class=>"btn btn-default"} %>
  </div>

<% end %>

</div>

app/views/people/_person_list.html.erb
<div class="row">
  <table class="table">

    <thead>
      <tr>
        <th>PID</th>
        <th>Name</th>
        <th>Country</th>
        <th>ZIP</th>
        <th>City</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render 'person_search' %>
      <% @persons.each do |person| %>
        <tr>
          <td><%= link_to person.id, person %></td>
          <td><%= link_to person.fullname, person %></td>
          <td><%= unless person.country.blank?  then link_to person.country, people_path(country: person.country)   end %></td>
          <td><%= unless person.zip.blank?      then link_to person.zip,     people_path(zip:     person.zip.to_s)  end %></td>
          <td><%= unless person.city.blank?     then link_to person.city,    people_path(city:    person.city.to_s) end  %></td>
          <td><%= link_to 'Show', person %></td>
          <td><%= link_to 'Edit', edit_person_path(person) %></td>
          <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/people/_person_search.html.erb
<tr>
  <%= inline_form :person, url: people_path, method: :get  do |f| %>
    <td><%= f.input :id,        placeholder: "PID"  %></td>
    <td><%= f.input :lastname,  placeholder: "Lastname"  %></td>
    <td><%= f.input :country,   placeholder: "Country", inline_label: "Country", input_html: { width: "50px" }  %></td>
    <td><%= f.input :zip,       placeholder: "ZIP" %></td>
    <td><%= f.input :city,      placeholder: "City" %></td>
    <td colspan="3"><%= f.button :submit, "Search", class: 'form-control btn-primary' %></td>
  <% end %>
</tr>

app/views/people/_teams.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Team</th>
      <th>Bereich</th>
      <th>Event</th>
      <th>von</th>
      <th>bis</th>
      <th>Aktuell</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>ProdSHam1509_FIA</td>
      <td>Produktion</td>
      <td>FIA Hamburg 09/2015</td>
      <td>15.09.15</td>
      <td>20.12.15</td>
      <td></td>
      <td><%= link_to 'Show', "#" %></td>
    </tr>
    <tr>
      <td>ProdSHam1601_HAP</td>
      <td>Produktion</td>
      <td>HAP Hamburg 01/2016</td>
      <td>20.01.16</td>
      <td>10.04.16</td>
      <td>X</td>
      <td><%= link_to 'Show', "#" %></td>
    </tr>
    <tr>
      <td>DatenVerwaltungsteam</td>
      <td>Verwaltung</td>
      <td></td>
      <td>01.01.16</td>
      <td>31.12.16</td>
      <td>X</td>
      <td><%= link_to 'Show', "#" %></td>
    </tr>
    <tr>
      <td>ZT Frankfurt</td>
      <td>Zukunftsteam</td>
      <td></td>
      <td>01.01.16</td>
      <td>31.12.16</td>
      <td>X</td>
      <td><%= link_to 'Show', "#" %></td>
    </tr>

  </tbody>

  <% @data.each do |assignment| %>
    <tr>
      <td><%= assignment.group %></td>
      <td><%= assignment.role_type %></td>
      <td><%= link_to 'Show', assignment %></td>
      <td><%= link_to 'Edit', edit__person_team_assignment_path(assignment) %></td>
      <td><%= link_to 'Remove', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

  <% end %>
</table>

<div>
  <%= paginate @data %>
</div>

<div>
  <%= link_to 'Assign to team', new_person_team_assignment_path(person: person), {class: "btn btn-default"} %>
</div>

app/views/people/edit.html.erb
<div class="row">
  <h3>Edit Person : <%= @person %></h3>
</div>

<%= render 'person_edit' %>

app/views/people/index.html.erb
<div class="row">
  <h3>Persons</h3>
</div>

<%= render 'person_list' %>

<div class="row">
  <%= link_to 'Add Person', new_person_path %>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render @person %>

app/views/people/show.html.erb
<div class="row">
  <h3>Person : <%= @person %></h3>
</div>

<div class="row">
  <div class="col">
    <% # div class="tabbable" %>
      <%= bettertabs_bootstrap :person_tabs do |tab|
        tab.ajax :person,   locals: { person: @person }
        tab.ajax :events,   locals: { person: @person }
        tab.ajax :teams,    locals: { person: @person }
        tab.ajax :calls,    locals: { person: @person }
        tab.ajax :history,  locals: { person: @person }
      end
      %>
    </div>
  </div>
</div>