config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :user
  resources :users
  resources :people
  resources :events
  resources :teams


  resources :locations
  resources :regions

  resources :event_role_types
  resources :event_types

  resources :team_role_types
  resources :team_types

  resources :person_event_assignments
  resources :person_team_assignments

  resources :calls

  resources :import_jobs,         only: [:index, :show, :destroy]

  resource :import_teilnehmer,   only: [:new, :create]
  resource :import_absolventen,  only: [:new, :create]

  resource :export_absolventen,  only: [:new, :create]

  resources :report, only: [:index, :show] do
    get :export
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/team_types_controller.rb
class TeamTypesController < ApplicationController
  before_action :find_course_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @team_types = TeamType.all
    respond_with(@team_types)
  end

  def show
    respond_with(@team_type)
  end

  def new
    @team_type = TeamType.new
    respond_with(@team_type)
  end

  def edit
  end

  def create
    @team_type = TeamType.new(course_type_params)
    if @team_type.save
      redirect_to team_types_path, notice: "Successfully created CourseType"
    else
      respond_with(@team_type)
    end
  end

  def update
    @team_type.update(course_type_params)
    # respond_with(@team_type)
    redirect_to course_types_path, notice: "Successfully updated CourseType"
  end

  def destroy
    @team_type.destroy
    # respond_with(@team_type)
    redirect_to course_types_path, notice: "Successfully deleted CourseType"
  end

  private
    def find_course_type
      @team_type = TeamType.find(params[:id])
    end

    def course_type_params
      params.require(:course_type).permit(:description)
    end
end

app/views/team_types/_form.html.erb
<%= simple_form_for(@group_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/team_types/edit.html.erb
<h1>Editing Group Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @group_type %> |
<%= link_to 'Back', group_types_path %>

app/views/team_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Group Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_types.each do |team_type| %>
      <tr>
        <td><%= team_type.code %></td>
        <td><%= team_type.description %></td>
        <td><%# link_to 'Show', team_type %></td>
        <td><%= link_to 'Edit', edit_team_type_path(team_type) %></td>
        <td><%= link_to 'Destroy', team_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group type', new_team_type_path %>

app/views/team_types/new.html.erb
<h1>New Group Type</h1>

<%= render 'form' %>

<%= link_to 'Back', group_types_path %>

app/views/team_types/show.html.erb
<p id="notice"><%= notice %></p>

<%= show_object @group_type %>

<%= link_to 'Edit', edit_group_type_path(@group_type) %> |
<%= link_to 'Back', group_types_path %>