config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :user
  resources :users
  resources :people
  resources :events
  resources :teams


  resources :locations
  resources :regions

  resources :event_role_types
  resources :event_types

  resources :team_role_types
  resources :team_types

  resources :person_event_assignments
  resources :person_team_assignments

  resources :calls

  resources :import_jobs,         only: [:index, :show, :destroy]

  resource :import_teilnehmer,   only: [:new, :create]
  resource :import_absolventen,  only: [:new, :create]

  resource :export_absolventen,  only: [:new, :create]

  resources :report, only: [:index, :show] do
    get :export
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id            :integer          not null, primary key
#  event_type_id :integer
#  location_id   :integer
#  shortname     :string(255)
#  title         :string(255)
#  startdate     :date
#  enddate       :date
#  baseprice     :decimal(8, 2)
#  event_state   :integer          default(0), not null
#  created_at    :datetime
#  updated_at    :datetime
#

class Event < ActiveRecord::Base

  STATUSES = [:planning, :open, :started, :ended, :closed]
  enum event_state: STATUSES

  belongs_to :event_type
  belongs_to :location

  has_many   :person_event_assignments, dependent: :destroy

  validates :event_type_id, presence: true
  validates :location_id,   presence: true

  validates_presence_of  :startdate #, :enddate
  # validates :enddate, date: { :after_or_equal_to => :startdate }

  default_scope { joins(:event_type).order(:startdate) }

  # scope :open, -> { where(event_state: Event.open).order(:startdate)}

  def self.shortname_from_filename(filename)
    return if filename.blank?

    filename = filename.upcase
    if filename.start_with? "SEM"
      prefix  = "Sem"
      evtcode =  filename[11,3]
      loccode = filename[3,3]
      ym_code = filename[6,4]
    elsif filename.start_with? "WISUNLIMITED"
      prefix  = ""
      evtcode = "WIS"
      loccode = "EUR"
      ym_code = "0000"
    elsif filename.start_with? "WIS_FuEv"
      prefix  = ""
      evtcode = "WFW"
      loccode = "HAN"
      ym_code = filename[9,4]
    elsif filename.start_with? == "ILP"
      prefix  = ""
      evtcode = "ILP"
      loccode = "GER"
      ym_code = filename[3,3]
    else
      prefix  = ""
      evtcode = filename[0,3]
      loccode = filename[3,3]
      ym_code = filename[6,4]
    end
    return prefix + evtcode + loccode + ym_code
  end

  def self.search(search)
    if search
      events = where(nil)
      events = events.where("shortname like ?",   "%#{search[:shortname]}%" )   if search[:shortname].present?
      events = events.where("title like ?",       "%#{search[:title]}%")        if search[:title].present?
      events = events.where("description like ?", "%#{search[:description]}%")  if search[:description].present?
      events = events.where("location_id = ?",     search[:location].to_i )     if search[:location].present?
      events = events.where("event_state = ?",     search[:state].to_i )        if search[:state].present?
      events
    else
      where(nil)
    end

  end

  def to_s
    "#{id} #{event_type} in #{location} starting at #{startdate}"
  end

  def attendees
    self.person_event_assignments.includes(:person).order("people.lastname")
  end

  def assistants
    #self.assignments.joins(:role_type).joins(:person).includes(:role_type).includes(:person).order("people.lastname")
  end

  def startdate_code
    startdate.strftime("%y%m")
  end

  def year
    startdate.year
  end

  # --------------------------------------------------------

  def city=(city)
     l = Location.where(city: city).first
     self.location = l if l
  end

  def filename=(filename)
    self.shortname = Event.shortname_from_filename(filename)
  end

  def shortname=(shortname)
    super
    if shortname.start_with?("Sem")
      evtcode = shortname[0,6]
      loccode = shortname[6,3]
      ym_code = shortname[9,4]
    else
      evtcode = shortname[0,3]
      loccode = shortname[3,3]
      ym_code = shortname[6,4]
    end

    evt = EventType.where(code: evtcode).first
    if evt.nil?
      logger.error "EventType #{evtcode} not found"
    else
      self.event_type = evt
    end

    if self.location.nil?
      loc = Location.where(code: loccode).first
      self.location = loc
    end

    if self.startdate.nil? && ym_code
      self.startdate = "20" + ym_code + "01"   # Year Month and Day "01"
    end

  end


  before_save do
    #if self.filename.nil?
    #  self.filename = event_type.code + location.code + startdate_code
    #end
    if self.title.nil?
      self.title = event_type.description
    end
  end

end

app/models/event_type.rb
# == Schema Information
#
# Table name: event_types
#
#  id          :integer          not null, primary key
#  code        :string(255)      not null
#  description :string(255)      not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class EventType <  ActiveRecord::Base
  has_many :events

  def to_s
    code + ":" + description
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  VISIBLE_ATTRIBUTES =
  %w( id shortname title location startdate enddate baseprice event_state )

  def index
    @events = Event.search(params[:search]).order(startdate: :desc).take(15)
    respond_with(@events)
  end

  def show
    # @assignments = @event.assignments.includes(:role_type).includes(:person)
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:event_type_id, :title, :shortname, :location_id, :startdate, :enddate, :event_state, :state)
    end
end

app/views/events/_attendees.html.erb
<div>

  <table class="table">
    <%# debugger %>
    <% object && object.each do |attendee| %>
      <tr>
        <td><%= attendee.person %></td>
        <td><%# attendee.role_type %></td>
        <td><%= link_to 'Show', person_path(attendee.person) %></td>
        <td><%# link_to 'Edit', edit_assignment_path(attendee) %></td>
        <td><%= link_to 'Remove', attendee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <%# link_to 'Assign to course', new_role_path(person: @person), {class: "btn btn-default"} %>
</div>

app/views/events/_event.html.erb
<div  class="col-sm-5">
  <h3>Course Information</h3>

  <%= horizontal_form @event do |f| %>
    <%= f.association :event_type %>
    <%= f.input :id, readonly: true %>
    <%= f.input :title %>
    <%= f.input :shortname %>
    <%= f.association :location %>
    <%= f.input :startdate, :include_blank => true %>
    <%= f.input :enddate,   :include_blank => true %>
    <%= f.input :event_state, collection: Event::STATUSES %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/events/_event_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Shortname</th>
      <th>Title</th>
      <th>Location</th>
      <th>Startdate</th>
      <th>Enddate</th>
      <th>Coursestate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'events/event_search' %>

    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.shortname, event %></td>
        <td><%# event.event_type.try(:description) %>
            <%= event.title %></td>
        <td><%= event.location %></td>
        <td><%= event.startdate %></td>
        <td><%= event.enddate %></td>
        <td><%= event.event_state %></td>

        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <td><%= link_to 'Show', event %></td>
            <td><%# link_to 'Edit', edit_event_path(event) %></td>
            <td><%# link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td><%= link_to 'Subscribe to event', new_assignment_path(person: current_user, event: event), {class: "btn btn-default"} %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_event_search.html.erb
<tr>
  <%= inline_form :search, url: events_path, method: :get  do |f| %>
    <td><%= f.input :shortname, placeholder: "Short Name"  %></td>
    <td><%= f.input :title,     placeholder: "Title",    inline_label: "Title"  %></td>
    <td><%= f.input :location,  placeholder: "Location", collection: Location.all, prompt: "Alle Orte" %></td>
    <td></td>
    <td></td>
    <td><%= f.input :state,     placeholder: "State",    collection: Group.group_states, prompt: "Alle" %></td>
    <td span="2"><%= f.button :submit, "Search" %></td>
  <% end %>
</tr>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'event' %>

<%# link_to 'Show', @course %> |
<%# link_to 'Back', courses_path %>

app/views/events/index.html.erb
<div class="row">
  <h1>List of Events</h1>
</div>

<div class="row">
  <%= render 'event_list' %>
</div>

<br>

<div class="row">
  <%= link_to 'New Event', new_event_path %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'event' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div  class="col-sm-5">
  <div class="tabbable">
    <%= bettertabs_bootstrap :person do |tab| %>
      <%= tab.ajax :event do  %>
        <%= show_object @event, only: controller.class::VISIBLE_ATTRIBUTES %>
        <div class="row">
          Anzahl Teilnehmer: <%= @event.person_event_assignments.count %>
        </div>
        <div class="row">
          <%= link_to 'Edit', edit_event_path(@event), {class: "btn btn-default"} %>
          <%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<div class="col-sm-6">
  <div class="tabbable">
    <%= bettertabs_bootstrap :event_tabs do |tab|
      tab.ajax :attendees,  locals: { object: @event.attendees }
      tab.ajax :assistants, locals: { object: @event.assistants }
    end
    %>
  </div>
</div>