config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'

  devise_for :user
  resources :users
  resources :people
  resources :events
  resources :teams


  resources :locations
  resources :regions

  resources :event_role_types
  resources :event_types

  resources :team_role_types
  resources :team_types

  resources :person_event_assignments
  resources :person_team_assignments

  resources :calls

  resources :import_jobs,         only: [:index, :show, :destroy]

  resource :import_teilnehmer,   only: [:new, :create]
  resource :import_absolventen,  only: [:new, :create]

  resource :export_absolventen,  only: [:new, :create]

  resources :report, only: [:index, :show] do
    get :export
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/controllers/event_types_controller.rb
class EventTypesController < ApplicationController
  before_action :find_event_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @event_types = EventType.all
    respond_with(@event_types)
  end

  def show
    respond_with(@event_type)
  end

  def new
    @event_type = EventType.new
    respond_with(@event_type)
  end

  def edit
  end

  def create
    @event_type = EventType.new(event_type_params)
    if @event_type.save
      redirect_to event_types_path, notice: "Successfully created EventType"
    else
      respond_with(@event_type)
    end
  end

  def update
    @event_type.update(event_type_params)
    # respond_with(@event_type)
    redirect_to event_types_path, notice: "Successfully updated EventType"
  end

  def destroy
    @event_type.destroy
    # respond_with(@event_type)
    redirect_to event_types_path, notice: "Successfully deleted EventType"
  end

  private
    def find_event_type
      @event_type = EventType.find(params[:id])
    end

    def event_type_params
      params.require(:event_type).permit(:description)
    end
end

app/views/event_types/_form.html.erb
<%= form_for(@event_type) do |f| %>
  <% if @event_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_type.errors.count, "error") %> prohibited this course_type from being saved:</h2>

      <ul>
      <% @event_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_types/edit.html.erb
<h1>Editing Course Type</h1>

<%= render 'form' %>

<%# link_to 'Show', @course_type %>
<%# link_to 'Back', course_types_path %>

app/views/event_types/index.html.erb
<h1>Course Types</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @event_types.each do |event_type| %>
      <tr>
        <td><%= event_type.code %></td>
        <td><%= event_type.description %></td>
        <td><%# link_to 'Show', event_type %></td>
        <td><%= link_to 'Edit', edit_event_type_path(event_type) %></td>
        <td><%= link_to 'Destroy', event_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course type', new_event_type_path %>

app/views/event_types/new.html.erb
<h1>New Course Type</h1>

<%= render 'form' %>

<%= link_to 'Back', course_types_path %>

app/views/event_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @course_type.description %>
</p>

<%= link_to 'Edit', edit_course_type_path(@course_type) %> |
<%= link_to 'Back', course_types_path %>